import type { IntegrationDefinition } from '@/lib/integrations/types';

export const integrationRegistry: readonly IntegrationDefinition[] = [
  {
    id: 'supabase-auth',
    label: 'Supabase Auth',
    runtime: 'shared',
    category: 'auth',
    severity: 'critical',
    owner: 'platform',
    environments: ['prod', 'sandbox'],
    surfaces: ['web', 'mobile', 'backend', 'auth'],
    routes: ['/api/auth/login', '/api/generate', '/api/trips', '/api/account'],
    configuration: {
      type: 'env',
      requiredAllEnv: ['NEXT_PUBLIC_SUPABASE_URL', 'NEXT_PUBLIC_SUPABASE_ANON_KEY'],
    },
    fallback: {
      mode: 'required',
      description: 'No auth fallback. Cookie web and bearer mobile must stay coherent.',
    },
    checks: [
      {
        id: 'web-cookie-session',
        label: 'Cookie session stays valid on web routes',
        severity: 'critical',
        automated: true,
        surfaces: ['web', 'auth', 'backend'],
        expectedFailure: 'auth_expired',
      },
      {
        id: 'mobile-bearer-session',
        label: 'Bearer auth stays valid for Expo API calls',
        severity: 'critical',
        automated: true,
        surfaces: ['mobile', 'auth', 'backend'],
        expectedFailure: 'auth_expired',
      },
      {
        id: 'refresh-token-path',
        label: 'Expired access token refreshes cleanly',
        severity: 'critical',
        automated: true,
        surfaces: ['web', 'mobile', 'auth'],
        expectedFailure: 'auth_expired',
      },
    ],
  },
  {
    id: 'supabase-data',
    label: 'Supabase Database',
    runtime: 'server',
    category: 'auth',
    severity: 'critical',
    owner: 'platform',
    environments: ['prod', 'sandbox'],
    surfaces: ['web', 'mobile', 'backend', 'social', 'collaboration', 'media'],
    routes: ['/api/feed', '/api/messages/conversations', '/api/trips', '/api/users/recommendations'],
    configuration: {
      type: 'env',
      requiredAllEnv: ['NEXT_PUBLIC_SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'],
    },
    fallback: {
      mode: 'required',
      description: 'Core data plane. No graceful fallback once the user is authenticated.',
    },
    checks: [
      {
        id: 'service-role-present',
        label: 'Server routes requiring admin client have a service role key',
        severity: 'critical',
        automated: true,
        surfaces: ['backend', 'social', 'collaboration'],
        expectedFailure: 'missing_env',
      },
      {
        id: 'profile-billing-read',
        label: 'Billing and profile routes can read profile state',
        severity: 'high',
        automated: true,
        surfaces: ['backend', 'billing'],
      },
    ],
  },
  {
    id: 'supabase-storage',
    label: 'Supabase Storage',
    runtime: 'server',
    category: 'media',
    severity: 'high',
    owner: 'platform',
    environments: ['prod', 'sandbox'],
    surfaces: ['web', 'mobile', 'backend', 'media'],
    routes: ['/api/trips/[id]/photos', '/api/trips/[id]/documents'],
    configuration: {
      type: 'env',
      requiredAllEnv: ['NEXT_PUBLIC_SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'],
    },
    fallback: {
      mode: 'required',
      description: 'Photos/documents should fail explicitly with storage-specific errors.',
    },
    checks: [
      {
        id: 'signed-url-generation',
        label: 'Signed URLs are generated from canonical storage paths',
        severity: 'high',
        automated: true,
        surfaces: ['backend', 'media'],
        expectedFailure: 'provider_unavailable',
      },
      {
        id: 'upload-delete-cycle',
        label: 'Upload, list and delete operations stay coherent',
        severity: 'high',
        automated: true,
        surfaces: ['web', 'mobile', 'media'],
      },
    ],
  },
  {
    id: 'supabase-realtime',
    label: 'Supabase Realtime',
    runtime: 'shared',
    category: 'social',
    severity: 'medium',
    owner: 'social',
    environments: ['prod', 'sandbox'],
    surfaces: ['web', 'mobile', 'social', 'collaboration', 'notifications'],
    routes: ['/api/messages/conversations', '/api/notifications'],
    configuration: {
      type: 'env',
      requiredAllEnv: ['NEXT_PUBLIC_SUPABASE_URL', 'NEXT_PUBLIC_SUPABASE_ANON_KEY'],
    },
    fallback: {
      mode: 'graceful',
      description: 'Live updates can degrade to polling and explicit refresh.',
    },
    checks: [
      {
        id: 'message-sync',
        label: 'Messages and notifications do not depend on stale local state',
        severity: 'medium',
        automated: true,
        surfaces: ['web', 'mobile', 'collaboration', 'notifications'],
      },
    ],
  },
  {
    id: 'stripe-billing',
    label: 'Stripe Billing',
    runtime: 'server',
    category: 'billing',
    severity: 'critical',
    owner: 'growth',
    environments: ['prod', 'sandbox'],
    surfaces: ['web', 'mobile', 'backend', 'billing'],
    routes: ['/api/billing/checkout', '/api/billing/portal', '/api/billing/one-time', '/api/webhooks/stripe'],
    configuration: {
      type: 'env',
      requiredAllEnv: [
        'STRIPE_SECRET_KEY',
        'STRIPE_PRICE_ID',
        'STRIPE_PRICE_ID_YEARLY',
        'STRIPE_PRICE_ID_ONE_TIME',
        'STRIPE_WEBHOOK_SECRET',
      ],
      optionalEnv: ['NEXT_PUBLIC_APP_URL', 'NEXT_PUBLIC_SITE_URL'],
    },
    fallback: {
      mode: 'required',
      description: 'Premium checkout must fail loudly. No silent downgrade for paid surfaces.',
    },
    checks: [
      {
        id: 'checkout-create-session',
        label: 'Subscription checkout session creation works',
        severity: 'critical',
        automated: true,
        surfaces: ['web', 'billing', 'backend'],
        expectedFailure: 'billing_refused',
      },
      {
        id: 'one-time-trip-session',
        label: 'One-time trip checkout uses configured price',
        severity: 'critical',
        automated: true,
        surfaces: ['web', 'billing', 'backend'],
        expectedFailure: 'billing_refused',
      },
      {
        id: 'webhook-credits-entitlements',
        label: 'Stripe webhook updates entitlements and trip credits',
        severity: 'critical',
        automated: true,
        surfaces: ['backend', 'billing'],
        expectedFailure: 'billing_refused',
      },
    ],
  },
  {
    id: 'revenuecat-billing',
    label: 'RevenueCat Billing',
    runtime: 'shared',
    category: 'billing',
    severity: 'critical',
    owner: 'growth',
    environments: ['prod', 'sandbox'],
    surfaces: ['mobile', 'backend', 'billing'],
    routes: ['/api/billing/revenuecat/sync', '/api/billing/revenuecat/webhook', '/api/billing/status'],
    configuration: {
      type: 'env',
      requiredAllEnv: ['REVENUECAT_SECRET_API_KEY', 'REVENUECAT_WEBHOOK_SECRET'],
      optionalEnv: ['NEXT_PUBLIC_REVENUECAT_IOS_KEY', 'NEXT_PUBLIC_REVENUECAT_ANDROID_KEY'],
    },
    fallback: {
      mode: 'required',
      description: 'Native purchases must sync entitlements, otherwise premium gating becomes inconsistent.',
    },
    checks: [
      {
        id: 'webhook-auth',
        label: 'RevenueCat webhook validates bearer secret',
        severity: 'critical',
        automated: true,
        surfaces: ['backend', 'billing'],
        expectedFailure: 'billing_refused',
      },
      {
        id: 'sync-endpoint',
        label: 'Mobile sync endpoint merges store entitlements into billing state',
        severity: 'critical',
        automated: true,
        surfaces: ['mobile', 'backend', 'billing'],
        expectedFailure: 'billing_refused',
      },
      {
        id: 'store-key-coverage',
        label: 'Platform keys exist for iOS and Android purchase SDKs',
        severity: 'high',
        automated: false,
        surfaces: ['mobile', 'billing'],
        expectedFailure: 'sandbox_not_configured',
      },
    ],
  },
  {
    id: 'apple-oauth',
    label: 'Apple OAuth',
    runtime: 'mobile_build',
    category: 'auth',
    severity: 'high',
    owner: 'platform',
    environments: ['prod', 'sandbox'],
    surfaces: ['mobile', 'auth'],
    routes: ['/login', '/register'],
    configuration: {
      type: 'manual',
      notes: 'Configured in Supabase + Apple Developer console and validated on device.',
    },
    fallback: {
      mode: 'graceful',
      description: 'Email/password remains available if Apple Sign-In is unavailable.',
    },
    checks: [
      {
        id: 'apple-login-on-device',
        label: 'Apple Sign-In returns a valid Supabase session on iOS',
        severity: 'high',
        automated: false,
        surfaces: ['mobile', 'auth'],
        expectedFailure: 'auth_expired',
      },
    ],
  },
  {
    id: 'google-oauth',
    label: 'Google OAuth',
    runtime: 'mobile_build',
    category: 'auth',
    severity: 'high',
    owner: 'platform',
    environments: ['prod', 'sandbox'],
    surfaces: ['web', 'mobile', 'auth'],
    routes: ['/login', '/register'],
    configuration: {
      type: 'manual',
      notes: 'Configured in Supabase + Google Cloud OAuth console with valid redirect URIs.',
    },
    fallback: {
      mode: 'graceful',
      description: 'Email/password remains available if Google OAuth is unavailable.',
    },
    checks: [
      {
        id: 'google-login-redirect',
        label: 'Google OAuth returns to the requested screen after login',
        severity: 'high',
        automated: true,
        surfaces: ['mobile', 'web', 'auth'],
        expectedFailure: 'auth_expired',
      },
    ],
  },
  {
    id: 'resend-email',
    label: 'Resend Transactional Email',
    runtime: 'server',
    category: 'auth',
    severity: 'high',
    owner: 'platform',
    environments: ['prod', 'sandbox'],
    surfaces: ['web', 'backend', 'auth'],
    routes: ['/api/auth/send-verification', '/api/auth/reset-password'],
    configuration: {
      type: 'env',
      requiredAllEnv: ['RESEND_API_KEY', 'SUPABASE_SERVICE_ROLE_KEY', 'NEXT_PUBLIC_SUPABASE_URL'],
    },
    fallback: {
      mode: 'required',
      description: 'Verification and reset must return an explicit server error if email sending is unavailable.',
    },
    checks: [
      {
        id: 'verification-email',
        label: 'Verification flow can generate and send a magic link',
        severity: 'high',
        automated: true,
        surfaces: ['web', 'auth', 'backend'],
        expectedFailure: 'provider_unavailable',
      },
      {
        id: 'reset-password-email',
        label: 'Password reset email can be generated and sent',
        severity: 'high',
        automated: true,
        surfaces: ['web', 'auth', 'backend'],
        expectedFailure: 'provider_unavailable',
      },
    ],
  },
  {
    id: 'anthropic',
    label: 'Anthropic Claude',
    runtime: 'server',
    category: 'provider',
    severity: 'critical',
    owner: 'travel-data',
    environments: ['prod', 'sandbox'],
    surfaces: ['backend', 'generation'],
    routes: ['/api/generate', '/api/generate/preflight', '/api/generate/answer'],
    configuration: {
      type: 'env',
      requiredAllEnv: ['ANTHROPIC_API_KEY'],
    },
    fallback: {
      mode: 'provider_chain',
      description: 'Generation should surface provider unavailability and keep preflight coherent.',
    },
    probe: 'anthropic',
    checks: [
      {
        id: 'generate-main-llm',
        label: 'Primary itinerary generation can authenticate against Anthropic',
        severity: 'critical',
        automated: true,
        surfaces: ['backend', 'generation'],
        expectedFailure: 'provider_unavailable',
      },
    ],
  },
  {
    id: 'gemini',
    label: 'Google AI / Gemini',
    runtime: 'server',
    category: 'provider',
    severity: 'high',
    owner: 'travel-data',
    environments: ['prod', 'sandbox'],
    surfaces: ['backend', 'generation', 'maps'],
    routes: ['/api/health', '/api/generate'],
    configuration: {
      type: 'env',
      requiredAllEnv: ['GOOGLE_AI_API_KEY'],
    },
    fallback: {
      mode: 'provider_chain',
      description: 'Fallbacks should keep generation alive when Gemini enrichment is unavailable.',
    },
    probe: 'gemini',
    checks: [
      {
        id: 'gemini-provider-auth',
        label: 'Gemini provider key is valid',
        severity: 'high',
        automated: true,
        surfaces: ['backend', 'generation'],
        expectedFailure: 'provider_unavailable',
      },
    ],
  },
  {
    id: 'google-places',
    label: 'Google Places',
    runtime: 'server',
    category: 'provider',
    severity: 'high',
    owner: 'travel-data',
    environments: ['prod', 'sandbox'],
    surfaces: ['backend', 'generation', 'maps'],
    routes: ['/api/places/search', '/api/place-photo', '/api/generate'],
    configuration: {
      type: 'env',
      requiredAnyEnv: ['GOOGLE_PLACES_API_KEY', 'GOOGLE_MAPS_API_KEY'],
    },
    fallback: {
      mode: 'provider_chain',
      description: 'Search can fall back to SerpAPI/OSM data when Places is unavailable.',
    },
    probe: 'google_places',
    checks: [
      {
        id: 'places-search',
        label: 'Places search/auth returns OK without REQUEST_DENIED',
        severity: 'high',
        automated: true,
        surfaces: ['backend', 'maps', 'generation'],
        expectedFailure: 'provider_unavailable',
      },
    ],
  },
  {
    id: 'google-maps',
    label: 'Google Maps / Directions',
    runtime: 'shared',
    category: 'provider',
    severity: 'medium',
    owner: 'travel-data',
    environments: ['prod', 'sandbox'],
    surfaces: ['web', 'backend', 'maps'],
    routes: ['/api/directions', '/trip/[id]'],
    configuration: {
      type: 'env',
      requiredAnyEnv: ['GOOGLE_MAPS_API_KEY', 'NEXT_PUBLIC_GOOGLE_MAPS_API_KEY'],
    },
    fallback: {
      mode: 'provider_chain',
      description: 'Directions can degrade to static links when Maps embeds are unavailable.',
    },
    checks: [
      {
        id: 'directions-api',
        label: 'Directions endpoint has a valid server-side key',
        severity: 'medium',
        automated: true,
        surfaces: ['backend', 'maps'],
        expectedFailure: 'provider_unavailable',
      },
      {
        id: 'maps-embed-key',
        label: 'Client-side trip embeds have a public key when enabled',
        severity: 'medium',
        automated: false,
        surfaces: ['web', 'maps'],
        expectedFailure: 'missing_env',
      },
    ],
  },
  {
    id: 'serpapi',
    label: 'SerpAPI',
    runtime: 'server',
    category: 'provider',
    severity: 'high',
    owner: 'travel-data',
    environments: ['prod', 'sandbox'],
    surfaces: ['backend', 'generation', 'maps'],
    routes: ['/api/compare-prices', '/api/generate'],
    configuration: {
      type: 'env',
      requiredAllEnv: ['SERPAPI_KEY'],
    },
    fallback: {
      mode: 'provider_chain',
      description: 'Hotel and attraction enrichment should fall back to Google/OSM providers.',
    },
    probe: 'serpapi',
    checks: [
      {
        id: 'serpapi-account',
        label: 'SerpAPI account probe shows remaining quota',
        severity: 'high',
        automated: true,
        surfaces: ['backend', 'generation'],
        expectedFailure: 'provider_unavailable',
      },
    ],
  },
  {
    id: 'viator',
    label: 'Viator',
    runtime: 'server',
    category: 'provider',
    severity: 'medium',
    owner: 'travel-data',
    environments: ['prod', 'sandbox'],
    surfaces: ['backend', 'generation'],
    routes: ['/api/attractions', '/api/generate'],
    configuration: {
      type: 'env',
      requiredAllEnv: ['VIATOR_API_KEY'],
    },
    fallback: {
      mode: 'provider_chain',
      description: 'Activities can fall back to other attraction sources without blocking generation.',
    },
    probe: 'viator',
    checks: [
      {
        id: 'viator-search',
        label: 'Viator partner search accepts the configured key',
        severity: 'medium',
        automated: true,
        surfaces: ['backend', 'generation'],
        expectedFailure: 'provider_unavailable',
      },
    ],
  },
  {
    id: 'rapidapi-tripadvisor',
    label: 'RapidAPI TripAdvisor',
    runtime: 'server',
    category: 'provider',
    severity: 'high',
    owner: 'travel-data',
    environments: ['prod', 'sandbox'],
    surfaces: ['backend', 'generation'],
    routes: ['/api/compare-prices', '/api/generate'],
    configuration: {
      type: 'env',
      requiredAllEnv: ['RAPIDAPI_KEY'],
    },
    fallback: {
      mode: 'provider_chain',
      description: 'TripAdvisor enrichment can degrade to Google/Foursquare/OSM sources.',
    },
    probe: 'rapidapi_tripadvisor',
    checks: [
      {
        id: 'rapidapi-tripadvisor-search',
        label: 'RapidAPI TripAdvisor responds with a valid key',
        severity: 'high',
        automated: true,
        surfaces: ['backend', 'generation'],
        expectedFailure: 'provider_unavailable',
      },
    ],
  },
  {
    id: 'rapidapi-booking',
    label: 'RapidAPI Booking',
    runtime: 'server',
    category: 'provider',
    severity: 'medium',
    owner: 'travel-data',
    environments: ['prod', 'sandbox'],
    surfaces: ['backend', 'generation'],
    routes: ['/api/compare-prices'],
    configuration: {
      type: 'env',
      requiredAllEnv: ['RAPIDAPI_KEY'],
    },
    fallback: {
      mode: 'provider_chain',
      description: 'Hotel comparison can fall back to affiliate links and SerpAPI.',
    },
    checks: [
      {
        id: 'booking-compare-prices',
        label: 'Booking comparison route handles missing or invalid RapidAPI data gracefully',
        severity: 'medium',
        automated: true,
        surfaces: ['backend', 'generation'],
        expectedFailure: 'provider_unavailable',
      },
    ],
  },
  {
    id: 'rapidapi-airbnb',
    label: 'RapidAPI Airbnb',
    runtime: 'server',
    category: 'provider',
    severity: 'medium',
    owner: 'travel-data',
    environments: ['prod', 'sandbox'],
    surfaces: ['backend', 'generation'],
    routes: ['/api/compare-prices'],
    configuration: {
      type: 'env',
      requiredAllEnv: ['RAPIDAPI_KEY'],
    },
    fallback: {
      mode: 'provider_chain',
      description: 'Airbnb import/compare can degrade to direct links when RapidAPI is unavailable.',
    },
    checks: [
      {
        id: 'airbnb-compare-prices',
        label: 'Airbnb compare/import wrapper fails explicitly when RapidAPI is unavailable',
        severity: 'medium',
        automated: true,
        surfaces: ['backend', 'generation'],
        expectedFailure: 'provider_unavailable',
      },
    ],
  },
  {
    id: 'foursquare',
    label: 'Foursquare',
    runtime: 'server',
    category: 'provider',
    severity: 'low',
    owner: 'travel-data',
    environments: ['prod', 'sandbox'],
    surfaces: ['backend', 'generation'],
    routes: ['/api/generate', '/api/health'],
    configuration: {
      type: 'env',
      requiredAllEnv: ['FOURSQUARE_CLIENT_ID', 'FOURSQUARE_CLIENT_SECRET'],
    },
    fallback: {
      mode: 'provider_chain',
      description: 'Foursquare is a low-priority fallback after Google/SerpAPI/RapidAPI.',
    },
    checks: [
      {
        id: 'foursquare-fallback-source',
        label: 'Fallback venue source remains optional and never blocks generation',
        severity: 'low',
        automated: true,
        surfaces: ['backend', 'generation'],
        expectedFailure: 'provider_unavailable',
      },
    ],
  },
  {
    id: 'overpass',
    label: 'Overpass / OSM',
    runtime: 'server',
    category: 'provider',
    severity: 'medium',
    owner: 'travel-data',
    environments: ['prod'],
    surfaces: ['backend', 'generation', 'maps'],
    routes: ['/api/health', '/api/generate'],
    configuration: {
      type: 'builtin',
      optionalEnv: ['NOMINATIM_EMAIL'],
    },
    fallback: {
      mode: 'provider_chain',
      description: 'OSM data is public; failure should fall back to other sources and keep geocoding coherent.',
    },
    probe: 'overpass',
    checks: [
      {
        id: 'overpass-public-endpoint',
        label: 'Overpass public endpoint responds within timeout',
        severity: 'medium',
        automated: true,
        surfaces: ['backend', 'generation', 'maps'],
        expectedFailure: 'provider_unavailable',
      },
    ],
  },
  {
    id: 'nominatim',
    label: 'Nominatim Geocoding',
    runtime: 'server',
    category: 'provider',
    severity: 'medium',
    owner: 'travel-data',
    environments: ['prod'],
    surfaces: ['backend', 'generation', 'maps'],
    routes: ['/api/geocode/autocomplete', '/api/geocode/reverse'],
    configuration: {
      type: 'builtin',
      optionalEnv: ['NOMINATIM_EMAIL'],
    },
    fallback: {
      mode: 'provider_chain',
      description: 'Autocomplete and reverse geocode can fall back to Google Places when available.',
    },
    checks: [
      {
        id: 'geocode-fallback-order',
        label: 'Geocode endpoints respect provider fallback order and explicit errors',
        severity: 'medium',
        automated: true,
        surfaces: ['backend', 'maps'],
        expectedFailure: 'provider_unavailable',
      },
    ],
  },
  {
    id: 'wikimedia',
    label: 'Wikimedia / Wikipedia',
    runtime: 'server',
    category: 'provider',
    severity: 'low',
    owner: 'travel-data',
    environments: ['prod'],
    surfaces: ['backend', 'generation'],
    routes: ['/api/generate'],
    configuration: {
      type: 'builtin',
    },
    fallback: {
      mode: 'graceful',
      description: 'Image enrichment is optional and should never block generation or trip detail.',
    },
    checks: [
      {
        id: 'image-enrichment-optional',
        label: 'Image enrichment stays optional and degrades gracefully',
        severity: 'low',
        automated: true,
        surfaces: ['backend', 'generation'],
        expectedFailure: 'provider_unavailable',
      },
    ],
  },
  {
    id: 'expo-sharing',
    label: 'Expo Sharing',
    runtime: 'mobile_build',
    category: 'device',
    severity: 'medium',
    owner: 'mobile-platform',
    environments: ['prod', 'sandbox'],
    surfaces: ['mobile', 'sharing'],
    routes: ['/trip/[id]', '/profile'],
    configuration: {
      type: 'manual',
      notes: 'Validated on device with expo-sharing plugin and OS share sheet.',
    },
    fallback: {
      mode: 'graceful',
      description: 'If native share is unavailable, copying a link or exporting locally must still work.',
    },
    checks: [
      {
        id: 'native-share-sheet',
        label: 'Native share sheet opens for trip sharing and exported files',
        severity: 'medium',
        automated: true,
        surfaces: ['mobile', 'sharing'],
        expectedFailure: 'provider_unavailable',
      },
    ],
  },
  {
    id: 'expo-calendar',
    label: 'Expo Calendar',
    runtime: 'mobile_build',
    category: 'device',
    severity: 'medium',
    owner: 'mobile-platform',
    environments: ['prod', 'sandbox'],
    surfaces: ['mobile', 'calendar'],
    routes: ['/trip/[id]'],
    configuration: {
      type: 'manual',
      notes: 'Validated on device with expo-calendar plugin and platform calendar permissions.',
    },
    fallback: {
      mode: 'graceful',
      description: 'If device calendar export fails, .ics export and Google Calendar links remain available.',
    },
    checks: [
      {
        id: 'device-calendar-export',
        label: 'Trip activities can export to Apple Calendar on device',
        severity: 'medium',
        automated: true,
        surfaces: ['mobile', 'calendar'],
        expectedFailure: 'provider_unavailable',
      },
    ],
  },
  {
    id: 'sentry',
    label: 'Sentry',
    runtime: 'shared',
    category: 'observability',
    severity: 'medium',
    owner: 'platform',
    environments: ['prod', 'sandbox'],
    surfaces: ['web', 'backend', 'mobile', 'observability'],
    routes: ['/api/generate', '/global-error'],
    configuration: {
      type: 'env',
      requiredAnyEnv: ['NEXT_PUBLIC_SENTRY_DSN'],
      optionalEnv: ['SENTRY_ORG', 'SENTRY_PROJECT'],
    },
    fallback: {
      mode: 'graceful',
      description: 'The product should still work without Sentry, but errors become harder to diagnose.',
    },
    checks: [
      {
        id: 'client-server-capture',
        label: 'Client and server exceptions are captured when DSN is configured',
        severity: 'medium',
        automated: false,
        surfaces: ['web', 'backend', 'observability'],
        expectedFailure: 'provider_unavailable',
      },
    ],
  },
  {
    id: 'firebase-push',
    label: 'Firebase Push Notifications',
    runtime: 'shared',
    category: 'observability',
    severity: 'medium',
    owner: 'platform',
    environments: ['prod', 'sandbox'],
    surfaces: ['web', 'mobile', 'backend', 'notifications'],
    routes: ['/api/notifications', '/api/notifications/register-device'],
    configuration: {
      type: 'env',
      requiredAllEnv: ['FIREBASE_SERVICE_ACCOUNT_KEY'],
      optionalEnv: ['NEXT_PUBLIC_FIREBASE_VAPID_KEY'],
    },
    fallback: {
      mode: 'feature_flag',
      description: 'Push surfaces stay hidden while Firebase is not fully configured.',
    },
    checks: [
      {
        id: 'device-registration',
        label: 'Device tokens can register and receive notifications when flag is enabled',
        severity: 'medium',
        automated: false,
        surfaces: ['web', 'mobile', 'notifications'],
        expectedFailure: 'feature_flag_off',
      },
    ],
  },
  {
    id: 'feature-flags',
    label: 'Public Feature Flags',
    runtime: 'shared',
    category: 'configuration',
    severity: 'high',
    owner: 'platform',
    environments: ['prod', 'sandbox'],
    surfaces: ['web', 'mobile', 'backend', 'observability'],
    routes: ['/api/health', '/pricing', '/profile', '/explore'],
    configuration: {
      type: 'builtin',
      optionalEnv: [
        'NEXT_PUBLIC_ENABLE_SOCIAL_FEATURES',
        'NEXT_PUBLIC_ENABLE_PREMIUM_BILLING',
        'NEXT_PUBLIC_ENABLE_EXPERIMENTAL_SURFACES',
        'NARAE_ENABLE_EXTERNAL_PROVIDERS',
        'EXPO_PUBLIC_ENABLE_SOCIAL_FEATURES',
        'EXPO_PUBLIC_ENABLE_PREMIUM_BILLING',
        'EXPO_PUBLIC_ENABLE_EXPERIMENTAL_SURFACES',
        'EXPO_PUBLIC_ENABLE_EXTERNAL_PROVIDERS',
      ],
    },
    fallback: {
      mode: 'feature_flag',
      description: 'Flags are the official kill switch for social, premium, experimental and provider-heavy surfaces.',
    },
    checks: [
      {
        id: 'social-kill-switch',
        label: 'Social surfaces can be disabled without breaking navigation',
        severity: 'high',
        automated: true,
        surfaces: ['web', 'mobile', 'social'],
        expectedFailure: 'feature_flag_off',
      },
      {
        id: 'premium-kill-switch',
        label: 'Premium gates can be disabled without leaving dead CTAs',
        severity: 'high',
        automated: true,
        surfaces: ['web', 'mobile', 'billing'],
        expectedFailure: 'feature_flag_off',
      },
    ],
  },
] as const;

export const integrationRegistryById = new Map(
  integrationRegistry.map((integration) => [integration.id, integration]),
);
